title: Lars Timmer
logo: /assets/img/headshot.jpg
description:  <a href="https://lalutir.github.io/predicting-s-p-500/" target="_blank">"Predicting Vanguard's S&P500 project page"</a>
#show_downloads: true
theme: jekyll-theme-minimal
gh_sponsor: lalutir
github:
  is_project_page: false
markdown: GFM
