title: Lars Timmer
logo: /assets/img/headshot.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
gh_sponsor: lalutir

  defaults:
    # _docs
    - scope:
        path: ""
        type: main
      values:
        sidebar:
          nav: "main"
