title: Lars Timmer
logo: /assets/img/headshot.jpg
description:  #<a href="https://lalutir.github.io/Football-match-predictions" target="_blank">Football match predictions project page</a>
#show_downloads: true
theme: jekyll-theme-minimal
gh_sponsor: lalutir
github:
  is_project_page: false
markdown: GFM
